[commands]
    [commands.@COMMANDS_CLEARID@]
        name = "clear"
        desc = "clears the terminal screen"
    [commands.@COMMANDS_ECHOID@]
        name = "echo"
        desc = "prints text"
    [commands.@COMMANDS_EXITID@]
        name = "exit"
        desc = "closes this terminal"
    [commands.@COMMANDS_HELPID@]
        name = "help"
        desc = "show this help"
    [commands.@COMMANDS_PRINTID@]
        name = "print"
        desc = "prints text"
    [commands.@COMMANDS_QUITID@]
        name = "quit"
        desc = "closes this application"
    [commands.@COMMANDS_LOAD_DLLID@]
        name = "load_dll"
        desc = "loads a shared library"
    [commands.@COMMANDS_LOAD_MAPID@]
        name = "load_map"
        desc = "loads map from file"
    [commands.@COMMANDS_UPDATE_WORLDID@]
        name = "update_world"
        desc = "update world once"
    [commands.@COMMANDS_SETID@]
        name = "set"
        desc = "sets a variable"
    [commands.@COMMANDS_VALUEOFID@]
        name = "valueof"
        desc = "prints the value of a game variable"
    [commands.@COMMANDS_RELOAD_RESOURCES@]
        name = "reconfigure"
        desc = "reloads resources and configurations files"
    [commands.@COMMANDS_FIRE_ACTIONABLE@]
        name = "fire_actionable"
        desc = "sends a signal to an actionable (eg: opens/closes a door)"
    [commands.@COMMANDS_FIRE_ACTIVATOR@]
        name = "fire_activator"
        desc = "sends a signal to an activator (eg: presses a button)"

[variables]
    [variables.@VARIABLES_AVERAGE_FPSID@]
        name = "average_fps"
    [variables.@VARIABLES_TARGET_FPSID@]
        name = "target_fps"
    [variables.@VARIABLES_DISPLAY_DEBUG_DATAID@]
        name = "display_dbg_data"

[log]
    [[log.entry]]
        id = "terminal_commands.command_missing_name"
        fmt = "No name found for command {cmd_id}"

    [[log.entry]]
        id = "terminal_commands.load_dll.usage"
        fmt = "Usage: {arg0} <shared library path>"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading"
        fmt = "Loading {dll_path}"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading_failed"
        fmt = "Error loading library"

    [[log.entry]]
        id = "terminal_commands.load_map.usage"
        fmt = "Usage: {arg0} <map path>"

    [[log.entry]]
        id = "terminal_commands.set.usage"
        fmt = "Usage: {arg0} <variable> <value>"
    [[log.entry]]
        id = "terminal_commands.set.unknown_var"
        fmt = "Unknown variable: {var_name}"
    [[log.entry]]
        id = "terminal_commands.set.need_uint"
        fmt = "{value} is not an unsigned integer."
    [[log.entry]]
        id = "terminal_commands.set.is_read_only"
        fmt = "Error: {var_name} is read-only"

    [[log.entry]]
        id = "terminal_commands.get.usage"
        fmt = "Usage: {arg0} <variable>"
    [[log.entry]]
        id = "terminal_commands.get.unknown_var"
        fmt = "Unknown variable: {var_name}"

    [[log.entry]]
        id = "terminal_commands.reload.usage"
        fmt = "Usage: {arg0} <config file>"
    [[log.entry]]
        id = "terminal_commands.reload.fail"
        fmt = "Failed to reload resources from {file_path}"
    [[log.entry]]
        id = "terminal_commands.reload.success"
        fmt = "{file_path}: resources successfully reloaded"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Usage: {arg0} <activator id>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.need_uint"
        fmt = "Activator id should be a positive integer (got \"{value}\")"
    [[log.entry]]
        id = "terminal_commands.fire_activator.too_high"
        fmt = "Invalid value (got: {value}, max: {max_value})"

    [[log.entry]]
        id = "terminal_commands.general.help"
        fmt = "Available commands:"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Usage: {arg0} <activator id>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.invalid_integer"
        fmt = "Activator id should be a positive integer (got \"{value}\")"
    [[log.entry]]
        id = "terminal_commands.fire_activator.invalid_value"
        fmt = "Invalid value (got: {value}, max: {max_value})"

    [[log.entry]]
        id = "adapter.map_load_failure"
        fmt = "Failed to load map \"{path}\": {reason}"
    [[log.entry]]
        id = "adapter.unsupported_version"
        fmt = "Unsupported version \"{version}\" for map \"{path}\""
    [[log.entry]]
        id = "adapter.unknown_model_handle"
        fmt = "Unknown model handle ({model_handle}) encountered for operation '{operation}'"
    [[log.entry]]
        id = "adapter.trace.rotate_entity"
        fmt = "Rotating view entity {view_handle} to a target angle of {angle} radians"
    [[log.entry]]
        id = "adapter.name_not_found"
        fmt = "Name not found for {kind} {handle}"
    [[log.entry]]
        id = "adapter.non_coherent_entity"
        fmt = "Non coherent entity type for id {handle}, logic and view might be out of sync (internal error)"
    [[log.entry]]
        id = "adapter.unknown_view_entity"
        fmt = "Unknown view entity with id {view_handle}, logic and view might be out of sync (internal error)"

[tooltip]
    [[tooltip.entry]]
        id = "adapter.objective"
        fmt = "Your objective."
    [[tooltip.entry]]
        id = "adapter.hp"
        fmt = "HP: {hp}"
    [[tooltip.entry]]
        id = "adapter.hitbox"
        fmt = "Hitbox: ({top_left_x} ; {top_left_y}) to ({bottom_right_x} ; {bottom_right_y})"
    [[tooltip.entry]]
        id = "adapter.position"
        fmt = "Position: ({x} ; {y})"
    [[tooltip.entry]]
        id = "adapter.angle"
        fmt = "Angle: {angle}"
    [[tooltip.entry]]
        id = "adapter.activator"
        fmt = "Activator: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_target"
        fmt = "Target: {handle}, {name}"
    [[tooltip.entry]]
        id = "adapter.nameless_target"
        fmt = "Target: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_gate"
        fmt = "Gate: {handle}, {name}"
    [[tooltip.entry]]
        id = "adapter.nameless_gate"
        fmt = "Gate: {handle}"
