[commands]
    [commands.@COMMANDS_CLEARID@]
        name = "clear"
        desc = "clears the terminal screen"
    [commands.@COMMANDS_ECHOID@]
        name = "echo"
        desc = "prints text"
    [commands.@COMMANDS_EXITID@]
        name = "exit"
        desc = "closes this terminal"
    [commands.@COMMANDS_HELPID@]
        name = "help"
        desc = "show this help"
    [commands.@COMMANDS_PRINTID@]
        name = "print"
        desc = "prints text"
    [commands.@COMMANDS_QUITID@]
        name = "quit"
        desc = "closes this application"
    [commands.@COMMANDS_LOAD_DLLID@]
        name = "load_dll"
        desc = "loads a shared library"
    [commands.@COMMANDS_LOAD_MAPID@]
        name = "load_map"
        desc = "loads map from file"
    [commands.@COMMANDS_UPDATE_WORLDID@]
        name = "update_world"
        desc = "update world once"
    [commands.@COMMANDS_SETID@]
        name = "set"
        desc = "sets a variable"
    [commands.@COMMANDS_VALUEOFID@]
        name = "valueof"
        desc = "prints the value of a game variable"
    [commands.@COMMANDS_RELOAD_RESOURCES@]
        name = "reconfigure"
        desc = "reloads resources and configurations files"
    [commands.@COMMANDS_FIRE_ACTIONABLE@]
        name = "fire_actionable"
        desc = "sends a signal to an actionable (eg: opens/closes a door)"
    [commands.@COMMANDS_FIRE_ACTIVATOR@]
        name = "fire_activator"
        desc = "sends a signal to an activator (eg: presses a button)"

[variables]
    [variables.@VARIABLES_AVERAGE_FPSID@]
        name = "average_fps"
    [variables.@VARIABLES_TARGET_FPSID@]
        name = "target_fps"
    [variables.@VARIABLES_DISPLAY_DEBUG_DATAID@]
        name = "display_dbg_data"

[log]
    [[log.entry]]
        id = "terminal_commands.command_missing_name"
        fmt = "No name found for command {cmd_id}"

    [[log.entry]]
        id = "terminal_commands.load_dll.usage"
        fmt = "Usage: {arg0} <shared library path>"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading"
        fmt = "loading {dll_path}"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading_failed"
        fmt = "error loading library"

    [[log.entry]]
        id = "terminal_commands.load_map.usage"
        fmt = "Usage: {arg0} <map path>"

    [[log.entry]]
        id = "terminal_commands.set.usage"
        fmt = "Usage: {arg0} <variable> <value>"
    [[log.entry]]
        id = "terminal_commands.set.unknown_var"
        fmt = "Unknown variable: {var_name}"
    [[log.entry]]
        id = "terminal_commands.set.need_uint"
        fmt = "{value} is not an unsigned integer."
    [[log.entry]]
        id = "terminal_commands.set.is_read_only"
        fmt = "Error: {var_name} is read-only"

    [[log.entry]]
        id = "terminal_commands.get.usage"
        fmt = "Usage: {arg0} <variable>"
    [[log.entry]]
        id = "terminal_commands.get.unknown_var"
        fmt = "Unknown variable: {var_name}"

    [[log.entry]]
        id = "terminal_commands.reload.usage"
        fmt = "usage: {arg0} <config file>"
    [[log.entry]]
        id = "terminal_commands.reload.fail"
        fmt = "failed to reload resources from {file_path}"
    [[log.entry]]
        id = "terminal_commands.reload.success"
        fmt = "{file_path}: resources successfully reloaded"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Usage: {arg0} <activator id>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.need_uint"
        fmt = "Activator id should be an integer (got {value})"
    [[log.entry]]
        id = "terminal_commands.fire_activator.too_high"
        fmt = "Invalid value (got {value}, max {max_value})"

    [[log.entry]]
        id = "terminal_commands.general.help"
        fmt = "Available commands:"
