[commands]
    [commands.@COMMANDS_CLEARID@]
        name = "éponge"
        desc = "nettoie l'écran"
    [commands.@COMMANDS_ECHOID@]
        name = "echo"
        desc = "affiche du texte à l'écran"
    [commands.@COMMANDS_EXITID@]
        name = "sortir"
        desc = "ferme le terminal"
    [commands.@COMMANDS_HELPID@]
        name = "aide"
        desc = "affiche cette aide"
    [commands.@COMMANDS_PRINTID@]
        name = "impression"
        desc = "affiche du texte à l'écran"
    [commands.@COMMANDS_QUITID@]
        name = "quitter"
        desc = "ferme l’application"
    [commands.@COMMANDS_LOAD_DLLID@]
        name = "charge_dll"
        desc = "charge une bilbiothèque pour gérer le roBot"
    [commands.@COMMANDS_LOAD_MAPID@]
        name = "charge_carte"
        desc = "charge une carte depuis un fichier"
    [commands.@COMMANDS_UPDATE_WORLDID@]
        name = "maj_monde"
        desc = "avance le monde d’un tick dans le temps"
    [commands.@COMMANDS_SETID@]
        name = "maj"
        desc = "met à jour la valeur d’une variable"
    [commands.@COMMANDS_VALUEOFID@]
        name = "val"
        desc = "affiche la valeur d'une variable"
    [commands.@COMMANDS_RELOAD_RESOURCES@]
        name = "reconfigurer"
        desc = "recharge les fichiers de resources et de configuration"
    [commands.@COMMANDS_FIRE_ACTIONABLE@]
        name = "actionner"
        desc = "Envoie un signal à un actionnable (ex : ouvrir/fermer une porte)"
    [commands.@COMMANDS_FIRE_ACTIVATOR@]
        name = "activateur"
        desc = "Envoie un signal à un activateur (ex : appuyer sur un bouton)"

    [variables.@VARIABLES_AVERAGE_FPSID@]
        name = "fps_moyen"
    [variables.@VARIABLES_TARGET_FPSID@]
        name = "fps_cible"
    [variables.@VARIABLES_DISPLAY_DEBUG_DATAID@]
        name = "afficher_indices_debogage"

[log]
    [[log.entry]]
        id = "terminal_commands.command_missing_name"
        fmt = "La commande {cmd_id} n’est associée à aucun nom d’appel"

    [[log.entry]]
        id = "terminal_commands.load_dll.usage"
        fmt = "Utilisation : {arg0} <chemin vers la bibliothèque>"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading"
        fmt = "{dll_path} : chargement en cours"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading_failed"
        fmt = "Échec du chargement"

    [[log.entry]]
        id = "terminal_commands.load_map.usage"
        fmt = "Utilisation : {arg0} <chemin vers la carte>"

    [[log.entry]]
        id = "terminal_commands.set.usage"
        fmt = "Utilisation : {arg0} <variable> <valeur>"
    [[log.entry]]
        id = "terminal_commands.set.unknown_var"
        fmt = "{var_name} : variable non reconnue"
    [[log.entry]]
        id = "terminal_commands.set.need_uint"
        fmt = "{value} n’est pas un entier positif"
    [[log.entry]]
        id = "terminal_commands.set.is_read_only"
        fmt = "Erreur : {var_name} est en lecture seule"

    [[log.entry]]
        id = "terminal_commands.get.usage"
        fmt = "Utilisation : {arg0} <variable>"
    [[log.entry]]
        id = "terminal_commands.get.unknown_var"
        fmt = "{var_name} : variable non reconnue"

    [[log.entry]]
        id = "terminal_commands.reload.usage"
        fmt = "Utilisation : {arg0} <fichier de config>"
    [[log.entry]]
        id = "terminal_commands.reload.fail"
        fmt = "Erreur lors du chargement du fichier {file_path}"
    [[log.entry]]
        id = "terminal_commands.reload.success"
        fmt = "{file_path}: configuration chargée avec succès"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Utilisation : {arg0} <id d’activateur>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.need_uint"
        fmt = "Erreur : l’id \"{value}\" n’est pas un entier positif"
    [[log.entry]]
        id = "terminal_commands.fire_activator.too_high"
        fmt = "Erreur : l’id {value} dépasse la valeur maximale autorisée pour la carte (max: {max_value})"

    [[log.entry]]
        id = "terminal_commands.general.help"
        fmt = "Commandes disponibles :"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Utilisation: {arg0} <id d'activateur>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.need_uint"
        fmt = "Erreur : l'id \"{value}\" n’est pas un entier positif valide"
    [[log.entry]]
        id = "terminal_commands.fire_activator.too_high"
        fmt = "Erreur : l'id {value} dépasse la valeur maximale autorisée pour la carte (max: {max_value})"

    [[log.entry]]
        id = "state_holder.configure.config_load_failed"
        fmt = "Échec du chargement des resources (fichier : {file})"

    [[log.entry]]
        id = "overmap_collection.unknow_entity_move"
        fmt = "Tentative de déplacement d’une entité inconnue {{type: vue, is_mob:{is_mob}, handle:{handle}}}"
    [[log.entry]]
        id = "overmap_collection.moving_mob"
        fmt = "Déplacement du mob [id vue] {handle} vers ({x} ; {y})"
    [[log.entry]]
        id = "overmap_collection.moving_object"
        fmt = "Déplacement de l’objet [id vue] {handle} vers ({x} ; {y})"
    [[log.entry]]
        id = "overmap_collection.incompatible_rotate"
        fmt = "Demande de rotation pour un objet incompatible [id vue] {handle}"

    [[log.entry]]
        id = "actionable.none"
        fmt = "({x} ; {y}) : rien à activer ici"
    [[log.entry]]
        id = "actionable.gate.open"
        fmt = "Ouverture de porte en ({x} ; {y})"
    [[log.entry]]
        id = "actionable.gate.close"
        fmt = "Fermeture de porte en ({x} ; {y})"

    [[log.entry]]
        id = "bot_api.commit.invalid_handle"
        fmt = "[DLL] Identifiant cible {handle} invalide pour la décision {decision}"
    [[log.entry]]
        id = "bot_api.commit.sanitize"
        fmt = "[DLL] Valeur flotante {value} invalide pour le paramètre {parameter}"

    [[log.entry]]
        id = "bot_dll.required_load_failed"
        fmt = "Le chargement de la fonction {func_name} a échoué (fichier {file})"
    [[log.entry]]
        id = "bot_dll.required_load_failed"
        fmt = "Fonction facultative {func_name} non présente dans {file}"
    [[log.entry]]
        id = "bot_dll.required_load_failed"
        fmt = "Fonction facultative {func_name} chargée depuis {file}"

    [[log.entry]]
        id = "adapter.map_load_failure"
        fmt = "Erreur au chargement de la carte \"{path}\" : {reason}"
    [[log.entry]]
        id = "adapter.unsupported_version"
        fmt = "Version \"{version}\" non supportée pour la carte \"{path}\""
    [[log.entry]]
        id = "adapter.unknown_model_handle"
        fmt = "Id modèle inconnue ({model_handle}) pour l'opération '{operation}'"
    [[log.entry]]
        id = "adapter.trace.rotate_entity"
        fmt = "Rotation de l'entité vue {view_handle}. Nouvel angle de {angle} radians"
    [[log.entry]]
        id = "adapter.name_not_found"
        fmt = "Nom introuvable pour {kind} {handle}"
    [[log.entry]]
        id = "adapter.non_coherent_entity"
        fmt = "Type d'entité incohérent pour {handle}. La logique et la vue n'ont peut-être pas été synchronisés correctement (erreur interne)"
    [[log.entry]]
        id = "adapter.unknown_view_entity"
        fmt = "L'entité vue {view_handle} est introuvable. La logique et la vue n'ont peut-être pas été synchronisés correctement (erreur interne)"

[tooltip]
    [[tooltip.entry]]
        id = "adapter.objective"
        fmt = "Ton objectif."
    [[tooltip.entry]]
        id = "adapter.hp"
        fmt = "PV: {hp}"
    [[tooltip.entry]]
        id = "adapter.hitbox"
        fmt = "Boîte de collision: ({top_left_x} ; {top_left_y}) to ({bottom_right_x} ; {bottom_right_y})"
    [[tooltip.entry]]
        id = "adapter.position"
        fmt = "Position: ({x} ; {y})"
    [[tooltip.entry]]
        id = "adapter.angle"
        fmt = "Angle: {angle}"
    [[tooltip.entry]]
        id = "adapter.activator"
        fmt = "Activateur: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_target"
        fmt = "Cible: {handle}, {name}"
    [[tooltip.entry]]
        id = "adapter.nameless_target"
        fmt = "Cible: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_gate"
        fmt = "Portail: {handle}, {name}"
    [[tooltip.entry]]
        id = "adapter.nameless_gate"
        fmt = "Portail: {handle}"
