[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Benoît CORTIER <benoit.cortier@fried-world.eu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pathfinding = "2.0"
ninja_clown_bot = { "path" = "../../bindings/rust/ninja_clown_bot", version = "0.1" }
