[user]
    language.general = "fr.toml"
    language.commands = "fr.toml"
    language.log = "fr.toml"
    language.gui = "fr.toml"

    resource_pack = "resources/assets-2d.toml"

    # TODO:
    # language.log = ""  [liste déroulante] + "select lang file"
    # font = ""          [liste déroulante] + "select font file"
    # engine.tps = n     [champ d’entrée  ]
    # volume = n         [curseur <---#-> ]
    # resource_pack = "" [liste déroulante] + "select resource pack file"

    # resource_pack : fichier config "graphics" comme si dessous
