[user]
    language.general="en"
    language.commands="fr"

[graphics]
    [graphics.mobs]
        list = ["player", "scientist"]

        [graphics.mobs.player]
            id = @MOBS_PLAYERID@

        [graphics.mobs.player.downwards]
            frame-count = 1
            pos.x = 0
            pos.y = 64
            shift.y = -58
            width = 42
            height = 56

        [graphics.mobs.player.upwards]
            frame-count = 1
            pos.x = 73
            pos.y = 64
            shift.y = -58
            width = 41
            height = 56

        [graphics.mobs.player.rightwards]
            frame-count = 1
            pos.x = 116
            pos.y = 64
            shift.y = -58
            width = 29
            height = 56

        [graphics.mobs.player.leftwards]
            frame-count = 1
            pos.x = 43
            pos.y = 64
            shift.y = -58
            width = 29
            height = 56

        [graphics.mobs.scientist]
            id = @MOBS_SCIENTISTID@

        [graphics.mobs.scientist.downwards]
            frame-count = 1
            pos.x = 0
            pos.y = 64
            shift.y = -58
            width = 42
            height = 56

        [graphics.mobs.scientist.upwards]
            frame-count = 1
            pos.x = 73
            pos.y = 64
            shift.y = -58
            width = 41
            height = 56

        [graphics.mobs.scientist.rightwards]
            frame-count = 1
            pos.x = 116
            pos.y = 64
            shift.y = -58
            width = 29
            height = 56

        [graphics.mobs.scientist.leftwards]
            frame-count = 1
            pos.x = 43
            pos.y = 64
            shift.y = -58
            width = 29
            height = 56

    [graphics.tiles]
        list = ["chasm", "iron-tile", "concrete-tile", "tile-frame", "target-tile"]
        spacing.x = 51
        x-yshift = 0 # when going one left (51px), go neither left nor right

        spacing.y = 31
        y-xshift = 31 # when going one up (31px), also go 31px to the right

        width = 81
        height = 31

        [graphics.tiles.chasm]
            id = @TILES_CHASMID@
            frame-count = 1
            pos.x = 164
            pos.y = 0

        [graphics.tiles.iron-tile]
            id = @TILES_IRONID@
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.concrete-tile]
            id = @TILES_CONCRETEID@
            frame-count = 1
            pos.x = 82
            pos.y = 0

        [graphics.tiles.tile-frame]
            id = @TILES_FRAMEID@
            frame-count = 2
            pos.x = 0
            pos.y = 32

        [graphics.tiles.target-tile]
            id = @TILES_TARGETID@
            frame-count = 8
            pos.x = 2
            pos.y = 122

    [graphics.objects]
        list = ["button"]

        [graphics.objects.button]
            id = @OBJECTS_BUTTONID@
            frame-count = 1
            pos.x = 162
            pos.y = 32
            width = 17
            height = 24
            shift.y = -4 # the button shall be printed with a sprite starting 4 extra upwards from usual
            shift.x = 33
