[user]
    language.general="en"
    language.commands="en"
    language.gui="fr"

    # TODO:
    # language.log = ""  [liste déroulante] + "select lang file"
    # font = ""          [liste déroulante] + "select font file"
    # engine.tps = n     [champ d’entrée  ]
    # volume = n         [curseur <---#-> ]
    # resource_pack = "" [liste déroulante] + "select resource pack file"

    # resource_pack : fichier config "graphics" comme si dessous + assets graphiques
    #                 > proposer un pack en vue d’en haut plutôt qu’en vue isométrique


[graphics]
    [graphics.mobs]
        list = ["player", "scientist"]

        [graphics.mobs.player]
            id = @MOBS_PLAYERID@
            file = "resources/simple-assets.png"

        [graphics.mobs.player.downwards]
            frame-count = 1
            pos.x = 192
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.upwards]
            frame-count = 1
            pos.x = 208
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.rightwards]
            frame-count = 1
            pos.x = 208
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.leftwards]
            frame-count = 1
            pos.x = 192
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.uprightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.upleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.downrightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.downleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16


        [graphics.mobs.scientist]
            id = @MOBS_SCIENTISTID@
            file = "resources/simple-assets.png"

        [graphics.mobs.scientist.downwards]
            frame-count = 1
            pos.x = 192
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.upwards]
            frame-count = 1
            pos.x = 208
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.rightwards]
            frame-count = 1
            pos.x = 208
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.leftwards]
            frame-count = 1
            pos.x = 192
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.uprightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.upleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.downrightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.downleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16


    [graphics.tiles]
        list = ["chasm", "iron-tile", "concrete-tile", "tile-frame"]
        spacing.x = 32
        x-yshift = 0

        spacing.y = 32
        y-xshift = 0

        width = 32
        height = 32

        [graphics.tiles.chasm]
            id = @TILES_CHASMID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 32
            pos.y = 0

        [graphics.tiles.iron-tile]
            id = @TILES_IRONID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.concrete-tile]
            id = @TILES_CONCRETEID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.tile-frame]
            id = @TILES_FRAMEID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 160
            pos.y = 0

    [graphics.objects]
        list = ["button", "gate", "target"]

        [graphics.objects.button]
            id = @OBJECTS_BUTTONID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 65
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.gate]
            id = @OBJECTS_GATEID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 97
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.target]
            id = @OBJECTS_TARGETID@
            file = "resources/simple-assets.png"
            frame-count = 1
            pos.x = 128
            pos.y = 0
            width = 32
            height = 32
            shift.x = 0
